
improve logging
~~~~~~~~~~~~~~~~

include the commandline in the notification emails, plus context (node, user)


assert errors would be better included with the notification email
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The notification email contains the log, but misses the assert error::


    === altbackup_main: log truncate Fri May 10 15:30:02 CST 2013
    2013-05-10 15:30:03,235 __main__ INFO     interpreted day string None into 2013/05/10 
    2013-05-10 15:30:03,236 __main__ INFO     <Values at 0xb7e816ec: {'wanted': 'dybsvn svnsetup', 'target': None, 'targetnode': 'C', 'loglevel': 'INFO', 'logpath': '/home/blyth/cronlog/altbackup.log', 'ext': '.tar.gz', 'echo': False, 'source': None, 'logformat': '%(asctime)s %(name)s %(levelname)-8s %(message)s', 'base': '/data/env/tmp', 'keep': 3, 'day': '2013/05/10'}>
    2013-05-10 15:30:03,236 __main__ INFO     source     : /home/scm/backup/dayabay 
    2013-05-10 15:30:03,236 __main__ INFO     target     : /data/var/scm/alt.backup/dayabay 
    2013-05-10 15:30:03,236 __main__ INFO     alt_check /data/var/scm/alt.backup/dayabay ['dybsvn', 'svnsetup'] : checking sidecar dna matches locally recomputed   
    2013-05-10 15:30:03,237 __main__ INFO     looking for ['dybsvn'] source tarballs beneath /data/var/scm/alt.backup/dayabay from 2013/05/10 
    2013-05-10 15:30:03,270 __main__ WARNING  SKIPPING AS no dna for path /data/var/scm/alt.backup/dayabay/tracs/dybsvn/2013/05/10/104701/dybsvn.tar.gz 
    2013-05-10 15:30:03,293 __main__ INFO     found 1 matching tarballs


Thats in the cron toplevel log::

    [blyth@cms01 ~]$ cat  $CRONLOG_DIR/altbackup_.log 
    === altbackup_main: /home/blyth/env/scm/altbackup.py -o /home/blyth/cronlog/altbackup.log dump check_target
    Traceback (most recent call last):
      File "/home/blyth/env/scm/altbackup.py", line 584, in <module>
        main()
      File "/home/blyth/env/scm/altbackup.py", line 566, in main
        alt_check( target, cfg )
      File "/home/blyth/env/scm/altbackup.py", line 405, in alt_check
        assert npaths == expect[want], "expecting %s paths for %s BUT got %s  " % (expect[want], want, relpaths ) 
    AssertionError: expecting 2 paths for dybsvn BUT got ['svn/dybsvn/2013/05/10/104701/dybsvn-20496.tar.gz']  
    === altbackup_main: ERROR RC 1
    === altbackup_notify: FAILURE Fri May 10 15:31:02 CST 2013 /home/blyth/cronlog/altbackup.log cms01.phys.ntu.edu.tw : sending notification MAILTO blyth@hep1.phys.ntu.edu.tw
    [blyth@cms01 ~]$ 
    [blyth@cms01 ~]$ 


checking at source on WW
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Notice a connection timeout did not lead to non zero RC::

    [dayabay] /home/blyth > cat  $CRONLOG_DIR/altbackup_.log 
    ...
    Read from remote host cms01.phys.ntu.edu.tw: Connection timed out
    lost connection

    real    46m21.414s
    user    0m0.060s
    sys     0m1.469s
    === altbackup_main: completed without error RC 0


remedy : manual rerun from WW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The script is smart wrt not repeating already successful transfers

::

    [dayabay] /home/blyth/e > altbackup.py dump check_source transfer purge_target



